services:
  - type: web
    name: prufungskalender
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SQLITE_DB_PATH
        value: /var/data/prufungskalender.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
